
CXX = g++
CXXFLAGS = -g -Wall -MMD
LIBS = -lSDL2 -lSDL2_image -lSDL2_ttf
TARGET = main

SRCS = $(wildcard *.cpp)
OBJS = $(SRCS:.cpp=.o)
DEPS = $(SRCS:.cpp=.d)

$(TARGET): $(OBJS)
	$(CXX) -o $(TARGET) $^ $(LIBS)

# Include dependency files, which are auto-generated by the -MMD flag
-include $(DEPS)

%.o: %.cpp
	$(CXX) -c -o $@ $< $(CXXFLAGS)

.PHONY: clean

clean:
	rm -rf $(TARGET) *.o *.d *.gch core

